version: '3.5'
services:
  zabbix-web:
    build: /home/ec2-user/Dockerimages
    restart: always
    environment:  # Postgre database variables
      DB_SERVER_HOST: postgres-server
#      DB_SERVER_HOST: 10.133.209.135
      DB_SERVER_PORT: 5432
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server  # Zabbix related and Php variables
      ZBX_SERVER_NAME: Test Instance DB
      ZBX_POSTMAXSIZE: 64M
      PHP_TZ: "Asia/Kolkata"
      ZBX_MAXEXECUTIONTIME: 500
    depends_on:
      - postgres-server
      - zabbix-server
        #    volumes:
#     - /home/ec2-user/brand.conf.php:/usr/share/zabbix/local/conf/brand.conf.php
#     - /home/ec2-user/assets/img:/usr/share/zabbix/assets/img
#      - /home/pamapp-ojas/compact.png:/usr/share/zabbix/compact.png
#      - /home/pamapp-ojas/tcl_logo.png:/usr/share/zabbix/tcl_logo.png
#      - /home/pamapp-ojas/side_bar.png:/usr/share/zabbix/side_bar.png
    ports:    # Port where Zabbix UI is available
      - 80:8080
#      - 389:389
      - 443:443

  postgres-server:
    #    image: timescale/timescaledb:latest-pg13
#  postgres-server:    # The Postgres Database Service
    image: postgres:latest
    restart: always
    environment:   # Username, password and database name variables
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      DB_SERVER_PORT: 5432
      DB_SERVER_SCHEMA: public
      ENABLE_TIMESCALEDB: 'true'
    ports:    # Port where Zabbix proxy is available
      - 5432:5432

  zabbix-server:     # The main Zabbix Server Software Service
    image: zabbix/zabbix-server-pgsql:alpine-6.0-latest
    restart: always
    environment:   # The Postgres database value variable
      DB_SERVER_HOST: postgres-server
#      DB_SERVER_HOST: 10.133.209.135
      DB_SERVER_PORT: 5432
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
#      ZBX_HISTORYSTORAGETYPES: log,text #Zabbix configuration variables
      ZBX_DEBUGLEVEL: 1
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 5000
#      ZBX_HANODENAME: ojas-node1
#      ZBX_NODEADDRESS: 10.133.208.90:10051
    depends_on:
      - postgres-server
    volumes:  # Volumes for scripts and related files you can add
      - /usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
#    ports:    # Port where Zabbix proxy is available
#      - 10051:10051
#      - 443:443
#      - 25:25
  zabbix-agent2:
    image: zabbix/zabbix-agent2:alpine-6.0-latest
    links:
      - zabbix-server
    labels:
      com.zabbix.descripttion: "Zabbix agent"

